-- Additive migration: retain existing patient records and treatment plans.
ALTER TABLE treatment_plans ADD COLUMN IF NOT EXISTS tooth VARCHAR(30) NOT NULL DEFAULT '';
ALTER TABLE treatment_plans ADD COLUMN IF NOT EXISTS treatment_date DATE;
ALTER TABLE treatment_plans ADD COLUMN IF NOT EXISTS cost DOUBLE PRECISION CHECK (cost >= 0 AND cost < 'Infinity'::float8);
ALTER TABLE treatment_plans ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP;

CREATE TABLE IF NOT EXISTS patient_files (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INTEGER NOT NULL REFERENCES patients(id),
    filename VARCHAR(255) NOT NULL,
    stored_name VARCHAR(100) NOT NULL UNIQUE,
    mime VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP
);
CREATE INDEX IF NOT EXISTS patient_files_patient_id_idx ON patient_files(patient_id);
CREATE INDEX IF NOT EXISTS treatment_plans_patient_id_idx ON treatment_plans(patient_id);
CREATE INDEX IF NOT EXISTS clinical_notes_patient_id_idx ON clinical_notes(patient_id);
