-- Additive booking controls and patient identity data. Existing rows remain valid.
ALTER TABLE patients ADD COLUMN IF NOT EXISTS identity_no VARCHAR(11);
ALTER TABLE patients ADD COLUMN IF NOT EXISTS birth_date DATE;

CREATE UNIQUE INDEX IF NOT EXISTS patients_identity_no_uq
  ON patients(identity_no)
  WHERE identity_no IS NOT NULL AND identity_no <> '';

CREATE TABLE IF NOT EXISTS appointment_slot_overrides (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day DATE NOT NULL,
    slot_time TIME NOT NULL,
    is_open BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
    UNIQUE(day, slot_time)
);

CREATE INDEX IF NOT EXISTS appointment_slot_overrides_day_idx
  ON appointment_slot_overrides(day);
